version: '3.9'
services:
    backend:
        build: .
        container_name: server
        command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
        volumes:
            - .:/app
        ports:
            - '8000:8000'
        environment:
            - PYTHONUNBUFFERED=1
